### ISSUE TITLE
[Crash Report] Soldiers are making an IAE when onLivingUpdate and getPostBlock

### ISSUE THREAD

**Issue by Fogrits** [TheExceptionist/Coherent-Villages#13]
ava.lang.IllegalArgumentException: bound must be positive
    at java.util.Random.nextInt(Unknown Source)
    at net.theexceptionist.coherentvillages.entity.soldier.EntityVillagerGuard.getPostBlock(EntityVillagerGuard.java:143)
    at net.theexceptionist.coherentvillages.entity.soldier.EntityVillagerGuard.onLivingUpdate(EntityVillagerGuard.java:119)
    at net.minecraft.entity.EntityLivingBase.onUpdate(EntityLivingBase.java:2172)
    at net.minecraft.entity.EntityLiving.onUpdate(EntityLiving.java:377)
    at net.minecraft.world.World.updateEntityWithOptionalForce(World.java:1990)
    at net.minecraft.world.WorldServer.updateEntityWithOptionalForce(WorldServer.java:832)
    at net.minecraft.world.World.updateEntity(World.java:1952)
    at net.minecraft.world.World.redirect$updateEntity$zbb000(World.java:4114)
    at net.minecraft.world.World.updateEntities(World.java:1756)
    at net.minecraft.world.WorldServer.updateEntities(WorldServer.java:613)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:767)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
    at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:252)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Unknown Source)

Latest Beta (v1.1.0)
Minecraft 1.12.2

[Complete Crash Report](https://paste.dimdev.org/efeyohabay.mccrash)

**Comment by TheExceptionist** [comment]
Yea I missed an if statement, Thanks for reporting this. It should be fixed now

**Comment by TheExceptionist** [comment]
In the newer version that is

**Comment by TheExceptionist** [comment]
I'll close this issue once I hear from you that it's been resolved
