### ISSUE TITLE
Crash on Server On Load

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [TheExceptionist/Coherent-Villages#34]
https://gist.github.com/P3rf3ctXZer0/9d0d962f58e885ab82f71c0c563d3e77

"Caused by: java.lang.RuntimeException: Attempted to load class buo for invalid side SERVER
	at net.minecraftforge.fml.common.asm.transformers.SideTransformer.transform(SideTransformer.java:62)
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:256)
... 41 more"

**Comment by TheExceptionist** [comment]
Fully aware, fixed in the next update

**Comment by P3rf3ctXZer0** [comment]
Fixed
