### ISSUE TITLE
Coherent Villages setting beetroots to an age of 6, where it's clearly not allowed

### ISSUE THREAD

**Issue by Velocihater** [TheExceptionist/Coherent-Villages#42]
---- Minecraft Crash Report ----
// I blame asiekierka, author of FoamFix.

Time: 2018-10-29 00:13:22 CDT
Description: Ticking entity

java.lang.IllegalArgumentException: Cannot set property PropertyInteger{name=age, clazz=class java.lang.Integer, values=[0, 1, 2, 3]} to 6 on block minecraft:beetroots, it is not an allowed value
    at pl.asie.foamfix.common.FoamyBlockState.withProperty(FoamyBlockState.java:59)
    at net.minecraft.block.BlockCrops.withAge(BlockCrops.java:61)
    at net.minecraft.block.BlockCrops.getStateFromMeta(BlockCrops.java:251)
    at net.theexceptionist.coherentvillages.worldgen.villages.FrankStructurePieces$Field2.addComponentParts(FrankStructurePieces.java:577), c
    at net.minecraft.world.gen.structure.StructureStart.generateStructure(StructureStart.java:47)
    at net.minecraft.world.gen.structure.MapGenStructure.generateStructure(MapGenStructure.java:94)
    at net.minecraft.world.gen.ChunkGeneratorOverworld.populate(ChunkGeneratorOverworld.java:406)
    at net.minecraft.world.chunk.Chunk.populate(Chunk.java:1019)
    at net.minecraft.world.chunk.Chunk.populate(Chunk.java:999)
    at net.minecraftforge.common.chunkio.ChunkIOProvider.syncCallback(ChunkIOProvider.java:110)
    at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:94)
    at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:118)
    at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:89)
    at net.minecraft.world.gen.ChunkProviderServer.provideChunk(ChunkProviderServer.java:135)
    at net.minecraft.world.World.getChunkFromChunkCoords(World.java:310)
    at net.minecraft.world.ChunkCache.<init>(ChunkCache.java:37)
    at net.minecraft.pathfinding.PathNavigate.getPathToPos(SourceFile:113)
    at net.minecraft.pathfinding.PathNavigateGround.getPathToPos(SourceFile:51)
    at net.minecraft.pathfinding.PathNavigateGround.getPathToEntityLiving(SourceFile:73)
    at net.minecraft.pathfinding.PathNavigate.tryMoveToEntityLiving(SourceFile:147)
    at net.minecraft.entity.ai.EntityAIFollowParent.updateTask(SourceFile:81)
    at net.minecraft.entity.ai.EntityAITasks.onUpdateTasks(SourceFile:129)
    at net.minecraft.entity.EntityLiving.updateEntityActionState(EntityLiving.java:888)
    at net.minecraft.entity.EntityLivingBase.onLivingUpdate(EntityLivingBase.java:2352)
    at net.minecraft.entity.EntityLiving.onLivingUpdate(EntityLiving.java:678)
    at net.minecraft.entity.EntityAgeable.onLivingUpdate(EntityAgeable.java:178)
    at net.minecraft.entity.passive.EntityAnimal.onLivingUpdate(SourceFile:43)
    at lykrast.defiledlands.common.entity.passive.EntityBookWyrm.onLivingUpdate(EntityBookWyrm.java:131)
    at net.minecraft.entity.EntityLivingBase.onUpdate(EntityLivingBase.java:2172)
    at net.minecraft.entity.EntityLiving.onUpdate(EntityLiving.java:377)
    at net.minecraft.world.World.updateEntityWithOptionalForce(World.java:1993)
    at net.minecraft.world.WorldServer.updateEntityWithOptionalForce(WorldServer.java:832)
    at net.minecraft.world.World.updateEntity(World.java:1955)
    at net.minecraft.world.World.redirect$updateEntity$zbl000(World.java:4117)
    at net.minecraft.world.World.updateEntities(World.java:1759)
    at net.minecraft.world.WorldServer.updateEntities(WorldServer.java:613)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:767)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
    at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:252)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Unknown Source)

**Comment by TheExceptionist** [comment]
***sigh*** I'll get this fixed today
