### ISSUE TITLE
Ticking Entity Error

### ISSUE THREAD

**Issue by ThighHighSuccubi** [TheExceptionist/Coherent-Villages#43]
Not very smart so I have no clue if this is a thing on my end or a fault with the mod. Using absolute latest version with a bunch other things, no other mod was referenced in the logs. 

Time: 11/1/18 3:27 PM
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
    at java.util.regex.Matcher.appendReplacement(Unknown Source)
    at java.util.regex.Matcher.replaceAll(Unknown Source)
    at java.lang.String.replaceAll(Unknown Source)
    at net.theexceptionist.coherentvillages.main.events.EventImmigration.execute(EventImmigration.java:44)
    at net.theexceptionist.coherentvillages.main.entity.attributes.AttributeFaction.update(AttributeFaction.java:254)
    at net.theexceptionist.coherentvillages.main.entity.EntityHumanVillager.func_70636_d(EntityHumanVillager.java:558)
    at net.minecraft.entity.EntityLivingBase.func_70071h(EntityLivingBase.java:2172)
    at net.minecraft.entity.EntityLiving.func_70071h(EntityLiving.java:295)
    at net.minecraft.world.World.func_72866_a(World.java:1993)
    at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
    at net.minecraft.world.World.func_72870_g(World.java:1955)
    at net.minecraft.world.World.func_72939_s(World.java:1759)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Unknown Source)

Full log  https://paste.dimdev.org/anamoqusaz.rb 

I've seen this happen with a different entity, same event was the immigration one. I think the last one was with a Mongol Shaman or something along those lines.

**Comment by TheExceptionist** [comment]
Ok, I'll see what I can do to fix it

**Comment by TheExceptionist** [comment]
Should be fixed in the next update
