### ISSUE TITLE
NPE Crash Ticking entity

### ISSUE THREAD

**Issue by pelletstove** [TheExceptionist/Coherent-Villages#47]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  LoadingPlugin (LootingModMC1.12.2-1.1.jar)
  LoadingPlugin (customport-1.12.2-1.0.jar)
  LoadingPlugin (Quark-r1.4-125.jar)
  IMLoadingPlugin (infinimend-1.12-1.0.2.jar)
  CorePlugin (ForgeEndertech-1.12.2-4.3.3.0-build.0095.jar)
  CreativePatchingLoader (CreativeCore_v1.9.22_mc1.12.2.jar)
Contact their authors BEFORE contacting forge

// Why did you do that?

Time: 11/10/18 5:31 PM
Description: Ticking entity

java.util.ConcurrentModificationException
	at java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:711)
	at java.util.LinkedHashMap$LinkedKeyIterator.next(LinkedHashMap.java:734)
	at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:125)
	at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:888)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2352)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:678)
	at net.minecraft.entity.EntityAgeable.func_70636_d(EntityAgeable.java:178)
	at net.theexceptionist.coherentvillages.main.entity.EntityHumanVillager.func_70636_d(EntityHumanVillager.java:1598)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2172)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:377)
	at net.minecraft.world.World.func_72866_a(World.java:1990)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1952)
	at net.minecraft.world.World.func_72939_s(World.java:1756)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:711)
	at java.util.LinkedHashMap$LinkedKeyIterator.next(LinkedHashMap.java:734)
	at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:125)
	at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:888)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2352)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:678)
	at net.minecraft.entity.EntityAgeable.func_70636_d(EntityAgeable.java:178)
	at net.theexceptionist.coherentvillages.main.entity.EntityHumanVillager.func_70636_d(EntityHumanVillager.java:1598)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2172)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:377)
	at net.minecraft.world.World.func_72866_a(World.java:1990)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1952)

-- Entity being ticked --
Details:
	Entity Type: coherentvillages:human_villager (net.theexceptionist.coherentvillages.main.entity.EntityHumanVillager)
	Entity ID: 322
	Entity Name: Jadzia - Slavic Novice Mage Archer
	Entity's Exact location: -146.30, 74.18, 155.45
	Entity's Block location: World: (-147,74,155), Chunk: (at 13,4,11 in -10,9; contains blocks -160,0,144 to -145,255,159), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Entity's Momentum: 0.00, -0.15, 0.01
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1756)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)

-- Affected level --
Details:
	Level name: Smoke
	All players: 2 total; [EntityPlayerMP['BuggaDaddy'/653, l='Smoke', x=-66.60, y=36.00, z=227.70], EntityPlayerMP['BlueCrayon13'/1123, l='Smoke', x=-65.32, y=37.00, z=226.75]]
	Chunk stats: ServerChunkCache: 426 Drop: 0
	Level seed: -2258502086495804847
	Level generator: ID 06 - RTG, ver 0. Features enabled: true
	Level generator options: {"seaLevel":63,"useBoulders":true,"boulderMult":1.0,"sandDuneHeight":4,"useSnowLayers":true,"bedrockLayers":5,"useCaves":true,"caveChance":8,"caveDensity":7,"useRavines":true,"ravineChance":100,"riverSizeMult":1.0,"riverFrequency":1.0,"riverBendMult":1.0,"riverCutOffAmpl":0.5,"riverCutOffScale":350.0,"RTGlakeSizeMult":1.0,"RTGlakeFreqMult":1.0,"RTGlakeShoreBend":1.0,"useWaterLakes":true,"waterLakeChance":10,"useLavaLakes":true,"lavaLakeChance":80,"useWaterUndLakes":true,"waterUndLakeChance":10,"useLavaUndLakes":true,"lavaUndLakeChance":80,"waterSpoutChance":200,"lavaSpoutChance":200,"useVillages":true,"villageSize":0,"villageDistance":48,"useMineShafts":true,"mineShaftChance":0.004,"useDungeons":true,"dungeonChance":8,"useTemples":true,"templeDistance":48,"useMonuments":true,"monumentSpacing":32,"monumentSeparation":5,"useMansions":true,"mansionSpacing":80,"mansionSeparation":20,"useStrongholds":true,"strongholdCount":128,"strongholdDistance":32,"strongholdSpread":3,"dirtSize":33,"dirtCount":10,"dirtMinHeight":0,"dirtMaxHeight":256,"gravelSize":33,"gravelCount":8,"gravelMinHeight":0,"gravelMaxHeight":256,"graniteSize":33,"graniteCount":10,"graniteMinHeight":0,"graniteMaxHeight":80,"dioriteSize":33,"dioriteCount":10,"dioriteMinHeight":0,"dioriteMaxHeight":80,"andesiteSize":33,"andesiteCount":10,"andesiteMinHeight":0,"andesiteMaxHeight":80,"coalSize":17,"coalCount":20,"coalMinHeight":0,"coalMaxHeight":128,"ironSize":9,"ironCount":20,"ironMinHeight":0,"ironMaxHeight":64,"goldSize":9,"goldCount":2,"goldMinHeight":0,"goldMaxHeight":32,"redstoneSize":8,"redstoneCount":8,"redstoneMinHeight":0,"redstoneMaxHeight":16,"diamondSize":8,"diamondCount":1,"diamondMinHeight":0,"diamondMaxHeight":16,"lapisSize":7,"lapisCount":1,"lapisCenterHeight":16,"lapisSpread":16}
	Level spawn location: World: (-196,64,256), Chunk: (at 12,4,0 in -13,16; contains blocks -208,0,256 to -193,255,271), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 18312 game time, 18312 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 7230 (now: false), thunder time: 1465 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2054058912 bytes (1958 MB) / 4771282944 bytes (4550 MB) up to 15992750080 bytes (15251 MB)
	LiteLoader Brand: 1.12.2-SNAPSHOT-r4CC2BB0-b4-4
	LiteLoader Mods: 1 loaded mod(s)
          - VoxelMap version 1.7.1
	LaunchWrapper: 29 active transformer(s)
          - Transformer: net.minecraftforge.fml.common.asm.transformers.PatchingTransformer
          - Transformer: optifine.OptiFineClassTransformer
          - Transformer: $wrapper.net.minecraftforge.fml.common.asm.transformers.BlamingTransformer
          - Transformer: $wrapper.net.minecraftforge.fml.common.asm.transformers.SideTransformer
          - Transformer: $wrapper.net.minecraftforge.fml.common.asm.transformers.EventSubscriptionTransformer
          - Transformer: $wrapper.net.minecraftforge.fml.common.asm.transformers.EventSubscriberTransformer
          - Transformer: $wrapper.net.minecraftforge.fml.common.asm.transformers.SoundEngineFixTransformer
          - Transformer: $wrapper.afdw.customport.ClassTransformer
          - Transformer: $wrapper.net.crazysnailboy.mods.infinimend.asm.IMClassTransformer
          - Transformer: $wrapper.com.ToMe.LootingMod.ClassTransformer
          - Transformer: $wrapper.vazkii.quark.base.asm.ClassTransformer
          - Transformer: org.spongepowered.asm.mixin.transformer.Proxy
          - Transformer: com.mumfrey.liteloader.transformers.event.EventProxyTransformer
          - Transformer: com.mumfrey.liteloader.launch.LiteLoaderTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.CrashReportTransformer
          - Transformer: net.minecraftforge.fml.common.asm.transformers.DeobfuscationTransformer
          - Transformer: net.minecraftforge.fml.common.asm.transformers.AccessTransformer
          - Transformer: net.minecraftforge.fml.common.asm.transformers.ModAccessTransformer
          - Transformer: net.minecraftforge.fml.common.asm.transformers.ItemStackTransformer
          - Transformer: net.minecraftforge.fml.common.asm.transformers.ItemBlockTransformer
          - Transformer: net.minecraftforge.fml.common.asm.transformers.ItemBlockSpecialTransformer
          - Transformer: org.spongepowered.asm.mixin.transformer.Proxy
          - Transformer: net.minecraftforge.fml.common.asm.transformers.TerminalTransformer
          - Transformer: org.spongepowered.asm.mixin.transformer.Proxy
          - Transformer: com.mumfrey.liteloader.transformers.event.EventTransformer
          - Transformer: com.mumfrey.liteloader.common.transformers.LiteLoaderPacketTransformer
          - Transformer: com.mumfrey.liteloader.transformers.event.json.ModEventInjectionTransformer
          - Transformer: org.spongepowered.asm.mixin.transformer.Proxy
          - Transformer: net.minecraftforge.fml.common.asm.transformers.ModAPITransformer
	JVM Flags: 5 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx15g -XX:CMSInitiatingOccupancyFraction=60 -XX:+UseCMSInitiatingOccupancyOnly -XX:+UseConcMarkSweepGC
	IntCache: cache: 1, tcache: 1, allocated: 8, tallocated: 60
	FML: MCP 9.42 Powered by Forge 14.23.4.2749 Optifine OptiFine_1.12.2_HD_U_E2 71 mods loaded, 71 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State     | ID                                   | Version             | Source                                                       | Signature                                |
	|:--------- |:------------------------------------ |:------------------- |:------------------------------------------------------------ |:---------------------------------------- |
	| UCHIJAAAA | minecraft                            | 1.12.2              | minecraft.jar                                                | None                                     |
	| UCHIJAAAA | mcp                                  | 9.42                | minecraft.jar                                                | None                                     |
	| UCHIJAAAA | FML                                  | 8.0.99.99           | forge-1.12.2-14.23.4.2749.jar                                | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | forge                                | 14.23.4.2749        | forge-1.12.2-14.23.4.2749.jar                                | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | creativecoredummy                    | 1.0.0               | minecraft.jar                                                | None                                     |
	| UCHIJAAAA | infinimend                           | 1.0.2               | minecraft.jar                                                | None                                     |
	| UCHIJAAAA | additionalstructures                 | 1.6.0               | Additional+Structures+1.12.2+by+XxRexRaptorxX++(v.1.6.0).jar | None                                     |
	| UCHIJAAAA | forgeendertech                       | 1.12.2-4.3.3.0      | ForgeEndertech-1.12.2-4.3.3.0-build.0095.jar                 | None                                     |
	| UCHIJAAAA | adhooks                              | 1.12.2-3.1.2.1      | AdHooks-1.12.2-3.1.2.1-build.0095.jar                        | None                                     |
	| UCHIJAAAA | quark                                | r1.4-125            | Quark-r1.4-125.jar                                           | None                                     |
	| UCHIJAAAA | autoreglib                           | 1.3-18              | AutoRegLib-1.3-18.jar                                        | None                                     |
	| UCHIJAAAA | baubles                              | 1.5.2               | Baubles-1.12-1.5.2.jar                                       | None                                     |
	| UCHIJAAAA | betterbuilderswands                  | 0.12.0              | BetterBuildersWands-1.12-0.12.0.251+d6c4d93.jar              | None                                     |
	| UCHIJAAAA | betteroffhand                        | 0.1                 | BetterOffhand-1.12.2-0.1.jar                                 | None                                     |
	| UCHIJAAAA | biomeinfo                            | v1.0                | biomeinfo-1.12.x-v1.0.jar                                    | None                                     |
	| UCHIJAAAA | bookshelf                            | 2.3.541             | Bookshelf-1.12.2-2.3.541.jar                                 | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCHIJAAAA | camoucreepers                        | 1.6                 | camoucreepers-1.6.jar                                        | None                                     |
	| UCHIJAAAA | carryon                              | 1.11.1              | CarryOn+MC1.12.2+v1.11.1.jar                                 | None                                     |
	| UCHIJAAAA | chameleon                            | 1.12-4.1.3          | Chameleon-1.12-4.1.3.jar                                     | None                                     |
	| UCHIJAAAA | clockhud                             | 1.4.0               | ClockHUD-1.12-1.4.0.jar                                      | None                                     |
	| UCHIJAAAA | coherentvillages                     | v0.0.5.8            | coherent_villages_pre-release_v0.0.5.8.jar                   | None                                     |
	| UCHIJAAAA | cosmeticarmorreworked                | 1.12.2-v3           | CosmeticArmorReworked-1.12.2-v3.jar                          | aaaf83332a11df02406e9f266b1b65c1306f0f76 |
	| UCHIJAAAA | cosmeticarmorreworked|tombmanygraves | 1.12.2-v3           | CosmeticArmorReworked-1.12.2-v3.jar                          | aaaf83332a11df02406e9f266b1b65c1306f0f76 |
	| UCHIJAAAA | crafttweaker                         | 4.0.12              | CraftTweaker2-1.12-4.0.12.jar                                | None                                     |
	| UCHIJAAAA | ctgui                                | 1.0.0               | CraftTweaker2-1.12-4.0.12.jar                                | None                                     |
	| UCHIJAAAA | jei                                  | 4.9.2.196           | jei_1.12.2-4.9.2.196.jar                                     | None                                     |
	| UCHIJAAAA | crafttweakerjei                      | 2.0.0               | CraftTweaker2-1.12-4.0.12.jar                                | None                                     |
	| UCHIJAAAA | creativecore                         | 1.9.9               | CreativeCore_v1.9.22_mc1.12.2.jar                            | None                                     |
	| UCHIJAAAA | customport                           | 1.0                 | customport-1.12.2-1.0.jar                                    | None                                     |
	| UCHIJAAAA | dirt2path                            | 1.7.0               | dirt2path-1.7.0.jar                                          | None                                     |
	| UCHIJAAAA | easiervillagertrading                | 1.2                 | easiervillagertrading-1.12-forge14.21.1.2387-1.2.jar         | None                                     |
	| UCHIJAAAA | csb_ench_table                       | 1.1.3               | EnchantingTable-1.12-1.1.3.jar                               | None                                     |
	| UCHIJAAAA | enchxchg                             | 1.0.6               | enchxchg-1.12.2-1.0.6.jar                                    | None                                     |
	| UCHIJAAAA | environmentalcreepers                | 1.4.0               | environmentalcreepers-1.12.2-1.4.0.jar                       | 2b03e1423915a189b8094816baa18f239d576dff |
	| UCHIJAAAA | expandedbonemeal                     | 1.2.1               | expandedbonemeal-1.11-1.2.1.jar                              | None                                     |
	| UCHIJAAAA | fastleafdecay                        | v14                 | FastLeafDecay-v14.jar                                        | None                                     |
	| UCHIJAAAA | harvestchevsky                       | b1                  | gentleharvest-1.12--b1.jar                                   | None                                     |
	| UCHIJAAAA | giacomosfoundry                      | 1.3.13              | GiacomosFoundry-1.12.2-1.3.13.jar                            | None                                     |
	| UCHIJAAAA | gravestone                           | 1.10.1              | gravestone-1.10.1.jar                                        | None                                     |
	| UCHIJAAAA | hopperducts                          | 1.5                 | hopperducts-mc1.12-1.5.jar                                   | None                                     |
	| UCHIJAAAA | horsetweaks                          | 1.0.4               | HorseTweaks_1.12.2-1.0.4.jar                                 | None                                     |
	| UCHIJAAAA | waila                                | 1.8.26              | Hwyla-1.8.26-B41_1.12.2.jar                                  | None                                     |
	| UCHIJAAAA | joypadsplitscreenmod                 | 1.12.0-0.22         | JoypadMod-1.12-14.21.0.2322.jar                              | None                                     |
	| UCHIJAAAA | keywizard                            | 1.10.2-1.5          | keywizard-1.12.2-1.5.2.jar                                   | None                                     |
	| UCHIJAAAA | lootingmod                           | 1.0                 | LootingModMC1.12.2-1.1.jar                                   | None                                     |
	| UCHIJAAAA | lucky                                | 7.5.0               | LuckyBlock_1-12_v7-5-0.zip                                   | None                                     |
	| UCHIJAAAA | examplemod                           | 1.0                 | modid-1.0.jar                                                | None                                     |
	| UCHIJAAAA | mobends                              | 0.25                | modid-1.0.jar                                                | None                                     |
	| UCHIJAAAA | nethergold                           | r3                  | Nether+Gold-1.12.2-r3.jar                                    | None                                     |
	| UCHIJAAAA | notenoughscaffold                    | 1.7                 | NotEnoughScaffold-1.12.2-1.7.jar                             | None                                     |
	| UCHIJAAAA | oreexcavation                        | 1.4.129             | OreExcavation-1.4.129.jar                                    | None                                     |
	| UCHIJAAAA | pitweaks                             | 1.12-0.5.5          | PiTweaks-1.12-0.5.5.jar                                      | None                                     |
	| UCHIJAAAA | playerrevive                         | 1.0                 | PlayerRevive_v1.2.13_mc1.12.2.jar                            | None                                     |
	| UCHIJAAAA | silentlib                            | 3.0.6               | SilentLib-1.12.2-3.0.6-154.jar                               | None                                     |
	| UCHIJAAAA | scalinghealth                        | 1.3.30              | ScalingHealth-1.12.2-1.3.30-131.jar                          | None                                     |
	| UCHIJAAAA | simpleleather                        | 1.12-1.0            | simpleleather-1.12-1.0.jar                                   | None                                     |
	| UCHIJAAAA | simpleminingdrills                   | 1.4.0               | simpleminingdrills+1.12.2.jar                                | None                                     |
	| UCHIJAAAA | spartanweaponry                      | beta 1.2.3          | SpartanWeaponry-1.12.2-beta-1.2.3.jar                        | None                                     |
	| UCHIJAAAA | stepup                               | 1.0.2-mc1.10-1.12.2 | StepUp-1.0.2-mc1.10-1.12.jar                                 | None                                     |
	| UCHIJAAAA | storagedrawers                       | 1.12-5.3.5          | StorageDrawers-1.12.2-5.3.7.jar                              | None                                     |
	| UCHIJAAAA | terracart                            | 1.12.2-1.2.3        | terracartreloaded-1.12.2-1.2.3.jar                           | None                                     |
	| UCHIJAAAA | tramplestopper                       | 1.2.2               | tramplestopper-1.12.2-1.2.2-universal.jar                    | None                                     |
	| UCHIJAAAA | trashslot                            | 8.4.6               | TrashSlot_1.12.1-8.4.6.jar                                   | None                                     |
	| UCHIJAAAA | upsizer                              | 4.0.1               | upsizer-mc1.12-4.0.1.jar                                     | None                                     |
	| UCHIJAAAA | va                                   | 1.12.2-1.5.2        | va-1.12.2-1.5.2.jar                                          | None                                     |
	| UCHIJAAAA | waterfreefarming                     | 2.0.5               | waterfreefarming-2.0.5.jar                                   | None                                     |
	| UCHIJAAAA | waystones                            | 4.0.67              | Waystones_1.12.2-4.0.67.jar                                  | None                                     |
	| UCHIJAAAA | wholetreeaxe                         | 1.7.1               | WholeTreeAxe-1.12-1.7.1.jar                                  | None                                     |
	| UCHIJAAAA | xpfromharvest                        | 1.0                 | xpfromharvest-1.12-1.0.1.jar                                 | None                                     |
	| UCHIJAAAA | rtg                                  | 6.1.0.0-beta.6      | RTG-1.12.2-6.1.0.0-beta.6.jar                                | None                                     |
	| UCHIJAAAA | totemexpansion                       | 1.2.2               | totemexpansion-1.2.2-1.12.2.jar                              | None                                     |

	Loaded coremods (and transformers): 
LoadingPlugin (LootingModMC1.12.2-1.1.jar)
  com.ToMe.LootingMod.ClassTransformer
LoadingPlugin (customport-1.12.2-1.0.jar)
  afdw.customport.ClassTransformer
LoadingPlugin (Quark-r1.4-125.jar)
  vazkii.quark.base.asm.ClassTransformer
IMLoadingPlugin (infinimend-1.12-1.0.2.jar)
  net.crazysnailboy.mods.infinimend.asm.IMClassTransformer
CorePlugin (ForgeEndertech-1.12.2-4.3.3.0-build.0095.jar)
  
CreativePatchingLoader (CreativeCore_v1.9.22_mc1.12.2.jar)
  
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 2 / 8; [EntityPlayerMP['BuggaDaddy'/653, l='Smoke', x=-66.60, y=36.00, z=227.70], EntityPlayerMP['BlueCrayon13'/1123, l='Smoke', x=-65.32, y=37.00, z=226.75]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge,LiteLoader'
	OptiFine Version: OptiFine_1.12.2_HD_U_E2
	OptiFine Build: 20180728-185429
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: KUDA-Shaders v6.1 Legacy.zip
	OpenGlVersion: 4.6.0 NVIDIA 397.64
	OpenGlRenderer: GeForce GTX 1080/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 16

**Comment by TheExceptionist** [comment]
I'll try to fix this as soon as possible. Taking a break right now

**Comment by TheExceptionist** [comment]
Check and see if the crash doesn't happen in the newest update
